//
//  Scrapbook+CoreDataClass.swift
//  Scrapbooks
//
//  Created by Dev User on 2017-07-24.
//  Copyright © 2017 Alan Li. All rights reserved.
//

import Foundation
import CoreData


public class Scrapbook: NSManagedObject {
    
    var fileDirectory: String {
        get {
            let documentDirectory = FileManager().urls(for: .documentDirectory, in: .userDomainMask).first
            return (documentDirectory?.appendingPathComponent(title).path)!
        }
    }
    
    func setup(withTitle newTitle: String) {
        title = newTitle
        moments = NSSet(array: [])
        
        do {
            try FileManager().createDirectory(atPath: fileDirectory, withIntermediateDirectories: false, attributes: nil)
        } catch (let error) {
            print("Creating scrapbook failed: \(String(describing: error))")
            fatalError()
        }
    }
    
    
    /// Properly removes a moment by deleting its accompanying photo from the filesystem as well.
    /// - Note: This remove should be called before the automatic remove generated by Core Data unless special customization is needed.
    func properlyRemove(moment: Moment) {
        
        let name = moment.name
        FileSystemHelper.removeFromDisk(photoWithName: name, forScrapbook: self)
        removeFromMoments(moment)
    }
}
